export const EVENT_FILTER_UPDATED = "EVENT_FILTER_UPDATED";
export const EVENT_QUEUE_WAIT_TIME_UPDATED = "EVENT_QUEUE_WAIT_TIME_UPDATED";
export const EVENT_SQUAD_MATCHED = "EVENT_SQUAD_MATCHED";
export const EVENT_USER_NOTIFICATION = "EVENT_USER_NOTIFICATION";
