import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RootProviders from "@/components/RootProviders";
import cx from "classnames";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

const allStar = localFont({
    src: "./Allstar4.ttf",
    variable: "--font-all-star",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={cx(inter.className, allStar.variable)}>
                <RootProviders session={await getServerSession(authOptions)}>
                    {children}
                </RootProviders>
            </body>
        </html>
    );
}
